insert into FLIGHT_REQUESTS
(ORIGIN_PLACE, DESTINATION_PLACE, OUTBOUND_DATE, INBOUND_DATE, ADULTS, CHILDREN,
    SERIAL_POLL_PERIOD, ENABLED_FLAG)
values ('KBP', 'ATH', '2019-12-01', '2019-12-12', 2, 1, 7, true);