-- one-way trip
insert into FLIGHT_REQUEST_SERVICE.FLIGHT_REQUESTS
(ORIGIN_PLACE, DESTINATION_PLACE, OUTBOUND_DATE, ADULTS, CHILDREN,
    SERIAL_POLL_PERIOD, ENABLED_FLAG)
values ('KBP', 'ATH', '2020-08-01', 2, 1, 7, true);

-- two-ways trip
insert into FLIGHT_REQUEST_SERVICE.FLIGHT_REQUESTS
(ORIGIN_PLACE, DESTINATION_PLACE, OUTBOUND_DATE, INBOUND_DATE, ADULTS, CHILDREN,
    SERIAL_POLL_PERIOD, ENABLED_FLAG)
values ('KBP', 'ATH', '2020-08-01', '2020-08-12', 2, 1, 7, true);